# -*- coding: utf-8 -*-
"""Untitled46.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZnIF3bvdUMbbfmXyUhPsjPUp78-HIr99
"""

import pandas as pd

df = pd.read_csv("/content/salary_prediction_data.csv")

df.shape

df.head()

df.info

df.isnull().sum()

from sklearn.preprocessing import LabelEncoder

"""### Applying Label Encoding

Label Encoding is a technique used to convert categorical labels into numerical values. Each unique category in a column is assigned a unique integer. This is useful for machine learning algorithms that require numerical input.

First, let's identify the categorical columns in your `df` DataFrame.
"""

# Identify categorical columns
categorical_cols = df.select_dtypes(include='object').columns

print("Categorical columns to be encoded:", categorical_cols)

# Initialize LabelEncoder
le = LabelEncoder()

# Apply Label Encoding to each categorical column
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])
    print(f"Column '{col}' encoded successfully.")

print("\nDataFrame after Label Encoding:")
display(df.head())

"""### Preparing Data for Regression Models

First, we need to separate our dataset into features (X) and the target variable (y). In this case, 'Salary' will be our target variable, and all other columns will be used as features to predict it. Then, we'll split the data into training and testing sets to evaluate our models effectively.
"""

from sklearn.model_selection import train_test_split

# Define features (X) and target (y)
X = df.drop('Salary', axis=1)
y = df['Salary']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print("Data split into training and testing sets successfully.")
print(f"X_train shape: {X_train.shape}")
print(f"X_test shape: {X_test.shape}")
print(f"y_train shape: {y_train.shape}")
print(f"y_test shape: {y_test.shape}")

"""### Comparing Multiple Regression Models

Now, let's build and evaluate a few different regression models to see which one performs best for predicting salary. We will compare:
1.  **Linear Regression**
2.  **Support Vector Machine (SVM) Regressor**
3.  **Decision Tree Regressor**
4.  **Random Forest Regressor**

We'll use the same `X_train`, `X_test`, `y_train`, and `y_test` splits we created earlier.
"""

from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Initialize a dictionary to store models and their performance
models = {
    'Linear Regression': LinearRegression(),
    'Support Vector Regressor': SVR(),
    'Decision Tree Regressor': DecisionTreeRegressor(random_state=42),
    'Random Forest Regressor': RandomForestRegressor(random_state=42)
}

results = {}

"""### Training and Evaluating Each Model

We will now iterate through each model, train it on the training data, make predictions on the test data, and then calculate its performance metrics.
"""

for name, model in models.items():
    print(f"\n--- Training {name} ---")
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    results[name] = {
        'MAE': mae,
        'MSE': mse,
        'RMSE': rmse,
        'R2 Score': r2
    }

    print(f"  Mean Absolute Error (MAE): {mae:.2f}")
    print(f"  Mean Squared Error (MSE): {mse:.2f}")
    print(f"  Root Mean Squared Error (RMSE): {rmse:.2f}")
    print(f"  R-squared (R2): {r2:.2f}")

"""### Summary of Model Performance

Let's compile and display the performance metrics for all models in a structured way for easy comparison.
"""

results_df = pd.DataFrame(results).T
print("\n--- Model Performance Summary ---")
display(results_df.sort_values(by='R2 Score', ascending=False))

display(results_df.sort_values(by='R2 Score', ascending=False))

import matplotlib.pyplot as plt
import seaborn as sns

# Prepare data for plotting
plot_df = results_df.reset_index().rename(columns={'index': 'Model'})

# Set up the matplotlib figure and axes for subplots
fig, axes = plt.subplots(1, 3, figsize=(20, 6))
fig.suptitle('Model Performance Comparison', fontsize=16)

# Plot MAE
sns.barplot(ax=axes[0], x='Model', y='MAE', data=plot_df.sort_values(by='MAE', ascending=True), palette='viridis', hue='Model', legend=False)
axes[0].set_title('Mean Absolute Error (MAE)')
axes[0].tick_params(axis='x', rotation=45)

# Plot RMSE
sns.barplot(ax=axes[1], x='Model', y='RMSE', data=plot_df.sort_values(by='RMSE', ascending=True), palette='viridis', hue='Model', legend=False)
axes[1].set_title('Root Mean Squared Error (RMSE)')
axes[1].tick_params(axis='x', rotation=45)

# Plot R2 Score
sns.barplot(ax=axes[2], x='Model', y='R2 Score', data=plot_df.sort_values(by='R2 Score', ascending=False), palette='viridis', hue='Model', legend=False)
axes[2].set_title('R-squared (R2 Score)')
axes[2].tick_params(axis='x', rotation=45)

plt.tight_layout(rect=[0, 0.03, 1, 0.95])
plt.show()

"""### Saving the Best Model

Based on our evaluation, the **Random Forest Regressor** demonstrated the best performance with the highest R-squared score and lowest error metrics. We will now save this trained model to a file using the `joblib` library. This allows us to reuse the model later without having to retrain it.
"""

import joblib

# Get the best performing model, which is 'Random Forest Regressor'
best_model_name = results_df.sort_values(by='R2 Score', ascending=False).index[0]
best_model = models[best_model_name]

# Define the filename for the saved model
model_filename = 'best_salary_prediction_model.pkl'

# Save the model to a file
joblib.dump(best_model, model_filename)

print(f"The best model ('{best_model_name}') has been saved to '{model_filename}'")

"""### Streamlit Application (`streamlit_app.py`)

This script will load your saved model and create a simple web interface where you can input feature values and get a salary prediction. You'll need to create a file named `streamlit_app.py` and copy the following code into it.

**Note:** For the categorical features (Education, Location, Job_Title, Gender), this simplified app expects you to input the *numerical values* that they were encoded to during training. In a production scenario, you would typically save and load your `LabelEncoder` objects to handle string inputs directly.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile streamlit_app.py
# 
# import streamlit as st
# import pandas as pd
# import joblib
# 
# # Load the trained model
# model = joblib.load('best_salary_prediction_model.pkl')
# 
# st.title('Salary Prediction App')
# st.write('Enter the details below to predict the salary.')
# 
# # Input fields for features (using numerical inputs for encoded categorical features)
# education = st.selectbox('Education (0=Bachelor, 1=High School, 2=Master, 3=PhD)', options=[0, 1, 2, 3]) # Assuming these are the encoded values
# experience = st.slider('Experience (Years)', min_value=0, max_value=50, value=10)
# location = st.selectbox('Location (0=Rural, 1=Suburban, 2=Urban)', options=[0, 1, 2]) # Assuming these are the encoded values
# job_title = st.selectbox('Job Title (0=Analyst, 1=Director, 2=Engineer, 3=Manager, 4=Sales)', options=[0, 1, 2, 3, 4]) # Assuming these are the encoded values
# age = st.slider('Age', min_value=18, max_value=70, value=30)
# gender = st.selectbox('Gender (0=Female, 1=Male)', options=[0, 1]) # Assuming these are the encoded values
# 
# if st.button('Predict Salary'):
#     # Create a DataFrame from the input values
#     input_data = pd.DataFrame([{
#         'Education': education,
#         'Experience': experience,
#         'Location': location,
#         'Job_Title': job_title,
#         'Age': age,
#         'Gender': gender
#     }])
# 
#     # Make prediction
#     predicted_salary = model.predict(input_data)[0]
# 
#     st.success(f'Predicted Salary: ${predicted_salary:,.2f}')
#

"""### Dependencies (`requirements.txt`)

This file tells Streamlit Cloud which Python libraries your application needs. Create a file named `requirements.txt` and copy the following content into it.
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile requirements.txt
# streamlit
# pandas
# scikit-learn
# joblib
#

"""### Deployment Steps for Streamlit Cloud

1.  **Download the files:**
    *   Download `best_salary_prediction_model.pkl` from your Colab environment (you can find it in the file browser on the left pane).
    *   Download `streamlit_app.py` (which you just created).
    *   Download `requirements.txt` (which you just created).

2.  **Create a GitHub Repository:**
    *   Create a new public GitHub repository (e.g., `salary-prediction-app`).
    *   Upload `best_salary_prediction_model.pkl`, `streamlit_app.py`, and `requirements.txt` to the root directory of this repository.

3.  **Deploy on Streamlit Cloud:**
    *   Go to [Streamlit Cloud](https://share.streamlit.io/).
    *   Sign in with your GitHub account.
    *   Click on 'New app' (or 'Deploy an app' if it's your first time).
    *   Select your GitHub repository and the `main` branch.
    *   For the 'Main file path', enter `streamlit_app.py`.
    *   Click 'Deploy!'

Streamlit Cloud will then build and deploy your application. This might take a few minutes. Once deployed, you'll get a public URL for your salary prediction app!
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import joblib
# 
# # Load the trained model
# model = joblib.load('best_salary_prediction_model.pkl')
# 
# st.title('Salary Prediction App')
# st.write('Enter the details below to predict the salary.')
# 
# # Input fields for features (using numerical inputs for encoded categorical features)
# education = st.selectbox('Education (0=Bachelor, 1=High School, 2=Master, 3=PhD)', options=[0, 1, 2, 3]) # Assuming these are the encoded values
# experience = st.slider('Experience (Years)', min_value=0, max_value=50, value=10)
# location = st.selectbox('Location (0=Rural, 1=Suburban, 2=Urban)', options=[0, 1, 2]) # Assuming these are the encoded values
# job_title = st.selectbox('Job Title (0=Analyst, 1=Director, 2=Engineer, 3=Manager, 4=Sales)', options=[0, 1, 2, 3, 4]) # Assuming these are the encoded values
# age = st.slider('Age', min_value=18, max_value=70, value=30)
# gender = st.selectbox('Gender (0=Female, 1=Male)', options=[0, 1]) # Assuming these are the encoded values
# 
# if st.button('Predict Salary'):
#     # Create a DataFrame from the input values
#     input_data = pd.DataFrame([{
#         'Education': education,
#         'Experience': experience,
#         'Location': location,
#         'Job_Title': job_title,
#         'Age': age,
#         'Gender': gender
#     }])
# 
#     # Make prediction
#     predicted_salary = model.predict(input_data)[0]
# 
#     st.success(f'Predicted Salary: ${predicted_salary:,.2f}')

import joblib
import pandas as pd

# Load the best model
model = joblib.load('best_salary_prediction_model.pkl')

# Define the input for prediction. We'll use 6 years of experience
# and reasonable default/modal values for other features based on our dataset.
# Encoded values (from earlier Label Encoding):
# Education: 0=Bachelor, 1=High School, 2=Master, 3=PhD
# Location: 0=Rural, 1=Suburban, 2=Urban
# Job_Title: 0=Analyst, 1=Director, 2=Engineer, 3=Manager, 4=Sales
# Gender: 0=Female, 1=Male

input_data = pd.DataFrame({
    'Education': [0],      # Assuming Bachelor's Degree
    'Experience': [6],     # 6 years of experience as requested
    'Location': [2],       # Assuming Urban location
    'Job_Title': [0],      # Assuming Analyst job title
    'Age': [30],           # Assuming Age 30
    'Gender': [0]          # Assuming Female
})

# Make the prediction
predicted_salary = model.predict(input_data)[0]

print(f"Predicted Salary for someone with 6 years of experience: ${predicted_salary:,.2f}")